apiVersion: v1
kind: ConfigMap
metadata:
    name: nginx-conf
data:
    nginx.conf: |
        events { worker_connections 1024; }
        http {
            upstream my_java_app {
                # ⚠️ 关键点：这里必须填第一步查出来的 PORT
                # 绝对不能填 8001 (那是 Ingress 的)
                # 如果 kubectl get svc 显示是 8002，这里就填 8002
                server java-app-svc:8002;
            }
            server {
                listen 80;
                location / {
                    proxy_pass http://my_java_app;

                    # 传递 Host 头，防止 Spring Boot 跳转时出错
                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                }
            }
        }
